- Generate 100 data points satisfying y = 2.1x + 3.4 + random_noise
- Use the builtin sklearn's LinearRegression() model to estimate the linear regression model from the data.
- Use gradient descent to estimate the model from the data
- How do your results in #2 and #3 compare?
- Modify the gradient descent algorithm to reduce the learning rate to 0.25 times the previous learning rate you used before, and run it to get the same results as before (i.e. the same coefficients).
- Did you have to run it the same steps, more, or, less? Why?

In [7]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [8]:
x = 2 * np.random.rand(100,1)
y = 3.4 + 2.1*x + np.random.randn(100,1)

In [9]:
X_b = np.c_[np.ones((100,1)), x]

In [10]:
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [11]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_b, y)

LinearRegression()

In [50]:
lrate = 0.2
iter = 50
m = 100
theta = np.random.randn(2,1)
print(theta)
for i in range(iter):
    grads = (2/m)*X_b.T.dot(X_b.dot(theta)-y)
    theta = theta - lrate*grads
    mse = mean_squared_error(X_b.dot(theta),y)
    print(theta, mse)

[[-1.09807922]
 [-0.50472088]]
[[1.65403331]
 [2.37150208]] 2.926348947047407
[[2.23467998]
 [2.86747631]] 1.1736757180246742
[[2.39845074]
 [2.91351774]] 1.0723249317736796
[[2.47957512]
 [2.87689501]] 1.0353452593289367
[[2.54188189]
 [2.82733886]] 1.0046851201175857
[[2.59771231]
 [2.77795049]] 0.9777635703460826
[[2.64959447]
 [2.73106151]] 0.954066986850127
[[2.69817732]
 [2.6869634 ]] 0.9332069486346313
[[2.74374174]
 [2.64556867]] 0.9148438374945423
[[2.78648881]
 [2.60672654]] 0.8986787708371131
[[2.82659532]
 [2.57028243]] 0.8844486450223998
[[2.86422487]
 [2.53608884]] 0.8719218497389414
[[2.89953054]
 [2.50400689]] 0.8608944981807922
[[2.93265585]
 [2.47390621]] 0.8511871085703261
[[2.96373546]
 [2.44566443]] 0.8426416829028418
[[2.9928957 ]
 [2.41916677]] 0.8351191353623811
[[3.02025511]
 [2.3943055 ]] 0.8284970285533769
[[3.04592491]
 [2.37097957]] 0.8226675807028984
[[3.07000943]
 [2.34909417]] 0.8175359113986157
[[3.09260658]
 [2.32856034]] 0.8130184973100143
[[3.1138082

In [51]:
print(theta)

[[3.38520007]
 [2.06268312]]


In [52]:
eta=0.1
n_iterations=100
theta_1=np.random.randn(2,1)
for iteration in range(n_iterations):
    gradients=2/m*X_b.T.dot(X_b.dot(theta_1)- y)
    theta_1=theta_1 - eta*gradients

In [53]:
print(theta_1)

[[3.38285693]
 [2.06481231]]


**We can see that both the coefficents are different for both the models.**

**Reducing the learning rate**

In [56]:
eta=0.001
n_iterations=1000
theta_2=np.random.randn(2,1)
for iteration in range(n_iterations):
    gradients=2/m*X_b.T.dot(X_b.dot(theta_2)- y)
    theta_2=theta_2 - eta*gradients

In [57]:
print(theta_2)

[[3.20413854]
 [2.15672979]]


In [72]:
eta=0.001
n_iterations=4000
theta_2=np.random.randn(2,1)
for iteration in range(n_iterations):
    gradients=2/m*X_b.T.dot(X_b.dot(theta_2)- y)
    theta_2=theta_2 - eta*gradients

In [73]:
print(theta_2)

[[3.27504923]
 [2.16277574]]


**We can see that after increasing the number of iterations, we can see that the theta value can be obtained.**